# Generated by Django 3.1.1 on 2020-09-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_new_djmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
