# Generated by Django 3.1.1 on 2020-09-29 10:29

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_new_djmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=django_fsm.FSMField(
                choices=[
                    ('OPEN', 'Open'),
                    ('CLOSED', 'Closed'),
                    ('DISABLED', 'Disabled')
                ],
                db_index=True,
                default='OPEN',
                max_length=20
            ),
        ),
    ]
