# Generated by Django 2.2.12 on 2020-09-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_new_djmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='delinquent',
            field=models.BooleanField(default=False),
        ),
    ]
