# Generated by Django 2.2.12 on 2020-10-08 09:08

import django.db.models.deletion
from django.db import migrations, models


def create_credit_card_relations(apps, schema_editor):
    Account = apps.get_model('billing', 'Account')
    CreditCard = apps.get_model('billing', 'CreditCard')
    accounts = Account.objects.all()
    for account in accounts:
        for transaction in account.transactions.all():
            try:
                credit_card = CreditCard.objects.get(
                    number=transaction.credit_card_number
                )
            except CreditCard.DoesNotExist:
                continue

            transaction.credit_card = credit_card
            transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_delinquent_flag_and_event_log_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transactions',
                to='billing.CreditCard'
            ),
        ),
        migrations.RunPython(create_credit_card_relations),
        migrations.RemoveField(
            model_name='transaction',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
    ]
