# Generated by Django 3.2.2 on 2021-05-10 09:19

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_update_delinquent_flag_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('NOK', 'Norwegian Krone'), ('CHF', 'Swiss Franc')], default='CHF', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('NOK', 'Norwegian Krone'), ('CHF', 'Swiss Franc')], default='CHF', editable=False, max_length=3),
        ),
    ]
